### ISSUE TITLE
could you show me how to work

### ISSUE THREAD

**Issue by EllenChiu** [CasperLaiTW/mlshb-child-accident#1]
could you show me how to work, website or ...?

**Comment by CasperLaiTW** [comment]
You can fill in this [form](http://goo.gl/forms/B4uj9CPk89)
And export **csv file** from the google docs [link](https://docs.google.com/spreadsheets/d/1xkuWs6k4RSrK01ZsC2743pjw8rFvLcH_j0Mh21EUdFU/edit?usp=sharing)

Finally please open the [web](http://child.health.i-uix.com/) and upload the **csv file** and get result.
The system didn't collect any info from your **csv file**
